config-version: 1.3

# listeners:
enable-pinglistener: false
# antidespawn makes:
# if player dies dropped items will not be able to despawn
# this feature is EXPERIMENTAL!
enable-antidespawn: true

# if pinglistener is enabled:
# ' ' is required for motd and icon name!
# place "icon.png" in your server root folder
# UPDATE: honestly i think "motd" is useless in my plugin
max-players: 10
motd: 'A Minecraft Server'
enable-icon: true
icon-file-name: 'icon.png'



# commands:

# silentcmd example:
# you: /gm 1 [target name]
# if command is not silent: server to target: "Your gamemode has been changed blah blah blah"
# if silent: nothing
# "- all" to execute all commands not silently
# commands aliases is acceptable
notsilent-commands:
# - god
# - food

# type commands what do you want to disable
# "- all" to disable all commands
# commands aliases is acceptable
disabled-commands:
# - god
# - food
